DeepBlueCLtd/RCO

README.md

Include command(s) to run the app

Hotfix - build instructions

---

src/App.tsx
src/providers/authProvider/index.ts
src/providers/dataProvider/index.ts
src/utils/audit.ts

22 Resolve Build Failure

---

src/App.tsx
src/providers/dataProvider/index.ts

Initial task

---

src/App.tsx
src/components/Layout/SideMenus.tsx
src/components/ReferenceDataList.tsx
src/pages/ReferenceData.tsx
src/pages/Welcome.tsx
src/providers/authProvider/index.ts
src/providers/dataProvider/index.ts
src/providers/dataProvider/reference-data.ts

Provide some reference tables
#5

Provide some reference tables

---

.eslintrc.json
Procfile
package.json
src/App.tsx
src/components/Layout/SideMenus.tsx
src/components/ProjectForm.tsx
src/providers/dataProvider/index.ts
src/resources/audit/AuditList.tsx
src/resources/projects/ProjectList.tsx
src/resources/projects/ProjectShow.tsx
src/resources/projects/index.tsx
src/types.d.ts
src/utils/audit.ts

Support for Projects

---

.eslintignore
src/providers/authProvider/index.ts
src/vite-env.d.ts
vite.config.ts

36 hotfix linter fixes

---

.eslintrc.json
.prettierrc.json
package.json
src/App.tsx
src/components/BatchForm.tsx
src/components/DatePicker.tsx
src/components/Layout/SideMenus.tsx
src/components/Layout/index.tsx
src/components/ReferenceDataList.tsx
src/components/SourceField.tsx
src/pages/ReferenceData.tsx
src/providers/dataProvider/index.ts
src/providers/dataProvider/reference-data.ts
src/providers/dataProvider/users.ts
src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/resources/batches/index.tsx
src/types.d.ts
tsconfig.json
yarn.lock

Support for batches

---

.prettierrc.json
src/App.tsx
src/pages/ReferenceData.tsx
src/providers/dataProvider/index.ts

46 vault locations

---

src/App.tsx
src/pages/ReferenceData.tsx
src/providers/dataProvider/index.ts

48 - Introduce media types

---

src/components/ItemForm/CoreForm.tsx
src/components/ReferenceDataList.tsx
src/providers/dataProvider/reference-data.ts
src/resources/reference-data/index.tsx
src/types.d.ts

Tighten up use of TypeScript, especially specification of `foreign keys`.

Hotfix improved types

---

package.json
src/providers/dataProvider/index.ts
src/types.d.ts
src/utils/generateData.ts
yarn.lock

created mock data for project, batch and platform

---

src/resources/items/ItemList.tsx

Removed nested filteres temporarily #14

Removed nested filteres temporarily

---

src/providers/dataProvider/index.ts

linter fix

---

src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemList.tsx
src/utils/generateData.ts

Store time for items

---

vite.config.ts

resolved yarn build fail

---

src/providers/dataProvider/index.ts
src/resources/projects/ProjectList.tsx

name filter on project list

---

src/App.tsx
src/pages/ReferenceData.tsx
src/resources/platforms/PlatformList.tsx
src/resources/platforms/index.tsx

Added platform in reference items
fixes #77

Added platform in reference items

---

src/providers/dataProvider/index.test.ts
src/providers/dataProvider/index.ts

generateBatchId fixed

---

.husky/pre-push
src/providers/dataProvider/index.test.ts
src/types.d.ts
src/utils/generateData.ts

drop vault

---

.github/workflows/node_compile.yml
.husky/pre-push
src/providers/dataProvider/index.test.ts

Introduce GitHub action to test valid code

---

src/components/FieldWithLabel.tsx

Fixed dom error

---

src/providers/dataProvider/index.ts
src/resources/audit/AuditList.tsx
src/types.d.ts
src/utils/audit.ts

security related field added in audit table

---

src/components/Layout/index.tsx

footer overlapping content issue fixed. Fixes #118

---

src/resources/batches/BatchForm.tsx
src/resources/batches/index.tsx

added batch label on batch edit page

---

src/resources/audit/AuditList.tsx

Audit list filter

---

src/providers/dataProvider/index.test.ts
src/resources/batches/BatchForm.tsx
src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/types.d.ts
src/utils/generateData.ts

Added receipt note to the batchList, batchShow and batchForm

---

src/resources/batches/BatchForm.tsx
src/resources/projects/ProjectShow.tsx

added batch create for projects

---

src/providers/dataProvider/index.test.ts
src/resources/batches/BatchForm.tsx
src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/types.d.ts
src/utils/generateData.ts
src/utils/init-data.ts

Removed protective marking authority from batch resource

---

src/resources/batches/BatchList.tsx

Added project filter on batch listing

---

src/App.tsx
src/components/Layout/SideMenus.tsx

Come up with improved icons, that meet our context.
Fixes #53

53 Minor update to icons

---

src/resources/batches/BatchForm.tsx

Fixed batch create issue

---

src/components/Recent.tsx
src/resources/batches/BatchShow.tsx
src/resources/items/ItemForm/index.tsx

Show empty list and fixed pagination conflicts with recent batches

---

src/components/ReferenceDataList.tsx
src/providers/dataProvider/reference-data.ts
src/resources/batches/BatchForm.tsx
src/resources/reference-data/ReferenceDataForm.tsx
src/resources/reference-data/index.tsx
src/types.d.ts
src/utils/init-data.ts

added active field in department reference data

---

src/providers/dataProvider/index.test.ts
src/providers/dataProvider/index.ts

Fixed NaN issue in batchNumber field

Fixed NaN issue in batchNumber field

---

src/components/Printable/index.tsx
src/index.css

hide print/cancel buttons

---

src/providers/dataProvider/index.ts

Fixed: RCO page needs to be refreshed before new user can login

---

src/components/Recent.tsx

Set min width to 342px for recent

Set min width to 342px for recent

---

src/resources/batches/BatchReport.tsx
src/resources/items/ItemsReport.tsx
src/resources/reference-data/VaultReport.tsx
src/resources/reference-data/index.tsx

vault location muster list

---

src/App.tsx
src/components/Layout/index.tsx
src/constants.ts
src/providers/dataProvider/index.test.ts
src/providers/dataProvider/index.ts

data provider logging added in user menu

---

src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemList.tsx
src/resources/projects/ProjectList.tsx
src/resources/projects/ProjectShow.tsx

created at field added to list and show pages

---

src/components/DatePicker.tsx

Added current default year to date picker in batch create

---

src/resources/batches/index.tsx

switch to batch show after batch create

---

src/resources/batches/BatchShow.tsx
src/resources/items/ItemList.tsx
src/resources/items/ItemsReport.tsx
src/types.d.ts

asset report for items

---

src/components/DatePicker.tsx

137 year of receipt

---

src/pages/Welcome.tsx

Created button on welcome page for vault location

---

src/App.tsx
src/components/Recent.tsx
src/constants.ts
src/pages/Welcome.tsx
src/resources/batches/BatchShow.tsx

Moved resource icons to constants

---

src/components/Printable/index.tsx
src/components/ReferenceDataList.tsx
src/components/ReportSignature.tsx
src/components/VaultLocationReport.tsx
src/index.css
src/resources/items/ItemsReport.tsx
src/resources/reference-data/index.tsx

Extensions for Vault Location List

---

src/resources/audit/AuditList.tsx

Added filters to audit listing

---

src/App.tsx
src/pages/Login.tsx

Added url params to login

---

src/resources/items/ItemList.tsx
src/resources/items/ItemShow.tsx

Minor changes in item listing

---

src/pages/ReferenceData.tsx

demoted some routes in reference data

---

src/resources/batches/BatchForm.tsx
src/resources/batches/BatchList.tsx
src/resources/platforms/PlatformList.tsx

149 is active flag platform

---

src/resources/items/ItemList.tsx
src/resources/projects/ProjectList.tsx

Added created at filter in item list and project list

---

src/providers/dataProvider/index.test.ts
src/resources/batches/BatchForm.tsx
src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/resources/projects/ProjectForm.tsx
src/resources/projects/ProjectList.tsx
src/resources/projects/ProjectShow.tsx
src/types.d.ts
src/utils/generateData.ts
src/utils/init-data.ts

Moved startDate, endDate and projectCode from project to Batch

---

src/resources/batches/BatchForm.tsx

default value set if there is only one item

---

src/components/ReferenceDataList.tsx
src/resources/batches/BatchForm.tsx
src/resources/reference-data/ReferenceDataForm.tsx
src/types.d.ts
src/utils/init-data.ts

Added isActive field 

---

src/resources/items/ItemForm/CoreForm.tsx

Added link on item show to parent batch

---

src/providers/authProvider/index.ts
src/providers/dataProvider/index.ts
src/resources/audit/AuditList.tsx
src/types.d.ts
src/utils/activity-types.ts
src/utils/audit.ts

Decoupled activity type from displayed label

---

src/App.tsx
src/components/ReferenceDataList.tsx
src/pages/ReferenceData.tsx
src/resources/audit/AuditList.tsx
src/resources/platforms/PlatformList.tsx
src/resources/platforms/index.tsx
src/resources/reference-data/index.tsx
src/resources/users/UserList.tsx
src/resources/users/index.tsx

Reference data converted to open in full page

---

src/components/VaultLocationReport.tsx
src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemList.tsx
src/types.d.ts
src/utils/generateData.ts

Added muster remarks to items

---

Procfile
vite.config.ts

heroku issue fixed

---

src/providers/authProvider/index.ts
src/providers/dataProvider/index.ts
src/resources/audit/AuditList.tsx
src/types.d.ts
src/utils/audit.ts

Extended audit log to include user id, item and resource

---

src/resources/items/ItemList.tsx

Loan filters#240

---

src/resources/items/ItemList.tsx
src/resources/items/LoanItemsListBulkActionButtons.tsx

Loan and loan returns for relevant items

---

src/resources/items/LoanItemsListBulkActionButtons.tsx

loan items only for active users

---

src/resources/audit/AuditList.tsx

Multiple selection filter for activity type field

---

src/constants.ts
src/providers/authProvider/index.ts
src/providers/dataProvider/dataprovider-utils.ts
src/providers/dataProvider/defaults/users.ts
src/providers/dataProvider/resource-callbacks/BatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/resource-callbacks/LoanCustomMethods.ts
src/providers/dataProvider/resource-callbacks/ProjectLifeCycle.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/providers/dataProvider/tests/batch.test.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/item.test.ts
src/resources/audit/AuditList.tsx
src/resources/batches/BatchForm.tsx
src/resources/items/ItemShow.tsx
src/resources/users/UserForm.tsx
src/types.d.ts
src/utils/audit.ts
src/utils/init-data.ts

Refactoring types, to allow auditing of more types of resources

Refactor types to include

---

src/constants.ts
src/providers/dataProvider/index.ts
src/providers/dataProvider/resource-callbacks/PlatformLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ProjectLifeCycle.ts
src/resources/users/index.tsx
src/utils/activity-types.ts

track changes for platform and project

---

src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/project.test.ts

tests written for project resource

---

src/resources/audit/AuditList.tsx

activity details column text wrap applied

---

src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/platform.test.ts

platform resource tests

---

src/App.tsx
src/components/Layout/SideMenus.tsx
src/pages/ReferenceData.tsx
src/resources/users/UserList.tsx

promoted users to left hand menu and versioning buf fixed

---

src/components/SourceField.tsx
src/components/SourceInput.tsx
src/providers/dataProvider/defaults/users.ts
src/resources/users/UserForm.tsx
src/resources/users/UserList.tsx
src/types.d.ts

added staff number to users

---

src/constants.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/user.test.ts
src/providers/dataProvider/tests/vaultLocation.test.ts

user resource and vault location tests

---

src/resources/users/UserShow.tsx
src/resources/users/index.tsx

user show permissions applied

---

src/providers/authProvider/permissions.ts

removed rco-user from editing reference data

---

src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/resources/users/UserList.tsx
src/utils/activity-types.ts

user return to organisation implemented

---

src/providers/dataProvider/dataprovider-utils.ts
src/providers/dataProvider/resource-callbacks/LoanCustomMethods.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/resources/audit/AuditList.tsx
src/types.d.ts
src/utils/audit.ts

added user to audit log for loaned item and for edit user

---

src/utils/init-data.ts

wipe all data before loading default data

---

package.json
src/constants.ts
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemForm/ItemFormToolbar.tsx
yarn.lock

Item create process modified

---

src/resources/items/ItemList.tsx

change location allow on loggedIn

---

src/resources/users/index.tsx

rco-user enable User create & edit

---

src/hooks/useDoubleClick.ts
src/resources/items/ItemList.tsx

Double click implemented on ItemList

---

src/components/Layout/index.tsx
src/providers/dataProvider/index.ts
src/resources/items/ItemShow.tsx
src/types.d.ts
src/utils/generateData.ts
src/utils/init-data.ts

assign items as loan to random users

---

src/hooks/useCanAccess.ts

fixed hard refresh issue

---

src/components/Printable/index.tsx
src/components/ReferenceDataList.tsx
src/components/ResourceHistory.tsx
src/resources/audit/AuditList.tsx
src/resources/batches/BatchShow.tsx
src/resources/items/ItemShow.tsx
src/resources/platforms/PlatformList.tsx
src/resources/projects/ProjectShow.tsx
src/resources/users/UserShow.tsx
src/resources/users/index.tsx
src/resources/vault-locations/VaultLocationList.tsx

285 history button

---

src/providers/dataProvider/tests/common.ts
src/providers/dataProvider/tests/department.test.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/reference-item.ts

department reference resource test written

---

src/resources/audit/AuditList.tsx

subject and user field linked to user show

---

.eslintrc.json
src/components/Layout/SideMenus.tsx

current resource permission checking call

---

src/components/VaultLocationReport.tsx
src/resources/vault-locations/VaultLocationList.tsx

vault location muster list bug fixed

---

src/providers/dataProvider/tests/common.ts
src/providers/dataProvider/tests/department.test.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/protective-marking-authority.test.ts
src/providers/dataProvider/tests/reference-item.ts

unit test written for protective-marking-authority reference item

---

src/components/CustomDatagridConfigurable.tsx
src/components/DblClickDatagridConfigurable.tsx
src/components/VaultLocationReport.tsx
src/resources/items/ItemList.tsx
src/resources/users/UserList.tsx
src/resources/vault-locations/VaultLocationList.tsx

double click handling

---

src/resources/batches/BatchForm.tsx

added start and end date in batch create form

---

src/providers/dataProvider/dataprovider-utils.ts
src/providers/dataProvider/resource-callbacks/BatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/tests/batch-generator.test.ts
src/providers/dataProvider/tests/batch.test.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/item.test.ts
src/resources/destruction/DestructionForm.tsx

drop leading zeroes

---

src/providers/dataProvider/resource-callbacks/BatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/DestructionLifeCycle.ts
src/providers/dataProvider/resource-callbacks/DispatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ProjectLifeCycle.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts

beforecreate type fix

---

src/providers/dataProvider/tests/batch-generator.test.ts
src/providers/dataProvider/tests/dummy-data.ts
src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/types.d.ts
src/utils/generateData.ts

projectCode dropped

---

src/components/ListWithLocalStore.tsx
src/hooks/useLocalStore.ts
src/resources/batches/BatchShow.tsx
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/items/ItemList.tsx
src/resources/users/UserShow.tsx
src/types.d.ts

add new item list for each component

---

src/components/FieldWithLabel.tsx
src/constants.ts
src/resources/dispatch/ReportData.tsx

to and from address shown on dispatch receipt note and hastener report

---

src/App.tsx
src/resources/destruction/DestructionList.tsx
src/resources/items/DestroyItems.tsx

destruction display remarks & live items dispatchedDate

---

src/types.d.ts
src/utils/init-data.ts

380 config table

---

src/App.tsx
src/constants.ts
src/pages/Welcome.tsx
src/providers/dataProvider/index.ts
src/providers/dataProvider/resource-callbacks/LoanCustomMethods.ts
src/resources/batches/BatchForm.tsx
src/resources/batches/BatchList.tsx
src/resources/batches/BatchReport.tsx
src/resources/batches/BatchShow.tsx
src/resources/dispatch/ReportData.tsx
src/resources/projects/ProjectForm.tsx
src/resources/projects/ProjectShow.tsx
src/resources/users/UserMusterList.tsx
src/types.d.ts
src/utils/useConfigData.ts

used config data from provider

---

src/resources/dispatch/HastenerReport.tsx
src/resources/dispatch/ReportData.tsx

full title added on hastener report

---

src/providers/dataProvider/tests/dummy-data.ts
src/resources/projects/ProjectForm.tsx
src/resources/projects/ProjectList.tsx
src/resources/projects/ProjectShow.tsx
src/types.d.ts
src/utils/generateData.ts

411 added start and end date for project resource

---

src/providers/dataProvider/tests/media-type.test.ts
src/providers/dataProvider/tests/organisation.test.ts
src/providers/dataProvider/tests/platform-originator.test.ts
src/providers/dataProvider/tests/protective-marking.test.ts

unit tests written

---

src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/item.test.ts
src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemForm/index.tsx
src/resources/items/ItemList.tsx
src/types.d.ts
src/utils/generateData.ts
src/utils/init-data.ts
src/utils/options.ts

set active mediatypes in itemcreate

---

src/resources/projects/ProjectShow.tsx

project show layout changed

---

src/components/ReferenceDataList.tsx
src/resources/platforms/PlatformList.tsx
src/resources/vault-locations/VaultLocationList.tsx

added id field on the reference data

---

src/resources/batches/BatchShow.tsx

batch show layout created

---

src/utils/date.ts

date comparison in audit modified

---

src/App.tsx
src/utils/init-data.ts

removed need for refresh on new instance

---

src/components/VaultLocationReport.tsx
src/resources/batches/BatchShow.tsx
src/resources/destruction/DestructionReport.tsx
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/dispatch/ReportData.tsx
src/resources/items/ItemsReport.tsx
src/resources/users/UserMusterList.tsx
src/resources/users/UserShow.tsx

item list fixed on batchshow, vaultlocation, destruction and dispatch

---

src/resources/batches/BatchShow.tsx
src/resources/users/UserShow.tsx

bulk action for item list fixed on batch show and user show

---

src/components/ProtectionBlockInputs.tsx
src/pages/ReferenceData.tsx
src/utils/init-data.ts
src/utils/useConfigData.ts

used config value where not being used

---

package.json
src/providers/dataProvider/tests/batch-generator.test.ts
src/resources/batches/BatchForm.tsx
src/resources/batches/index.tsx
src/resources/items/index.tsx
src/types.d.ts
src/utils/generateData.ts

make project/platform optional

---

src/resources/batches/BatchForm.tsx
src/resources/batches/BatchShow.tsx

batch show page changed to use batchform

---

src/resources/dispatch/ReportData.tsx

date format changed in dispatch report

---

src/resources/batches/BatchForm.tsx
src/resources/batches/index.tsx

redirect user to batch show after batch create

---

src/components/ProtectionBlockInputs.tsx
src/components/ProtectionRefInput.tsx
src/resources/batches/BatchForm.tsx
src/resources/batches/BatchList.tsx
src/resources/items/ItemForm/ItemFormToolbar.tsx
src/resources/items/ItemForm/index.tsx
src/resources/items/ItemList.tsx
src/types.d.ts
src/utils/helper.ts

code refactor for protection string

---

src/resources/items/ItemForm/ItemFormToolbar.tsx

changes button labels in create item

---

src/components/ProtectionRefInput.tsx
src/hooks/useRefTable.ts

user should stay on item create after creating item

---

src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemForm/index.tsx

fixed repeated refTable entries

---

src/components/DateFilter.tsx
src/components/DateRangePicker.tsx
src/resources/batches/BatchList.tsx
src/resources/items/ItemList.tsx
src/resources/projects/ProjectList.tsx

make date search working

---

src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/resources/items/ItemList.tsx
src/types.d.ts
src/utils/generateData.ts

removed project and platform from item resource

---

src/resources/items/DestroyItems.tsx
src/resources/items/DestroyRestoreItems.tsx
src/resources/items/DispatchItems.tsx
src/resources/items/ItemList.tsx

remove job term

---

src/resources/batches/BatchShow.tsx
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchShow.tsx

catch some remaining `job` references

---

src/resources/items/ItemList.tsx

items page crashing issue fixed

---

src/providers/dataProvider/tests/batch-generator.test.ts
src/providers/dataProvider/tests/dummy-data.ts
src/utils/generateData.ts

Forgot to use correct case for default data.

use correct case for VAULT name

---

src/resources/items/ItemList.tsx

item list sticky header issue fixed

---

src/resources/platforms/index.tsx

set correct resource in index file

---

db/Scripts/full.sql
src/components/ProtectionBlockInputs.tsx
src/constants.ts
src/pages/ReferenceData.tsx
src/types.d.ts
src/utils/init-data.ts

There were 3 remaining uses of snake-case in front-end.
Get rid of them.
Supports #471

move from snake case to camel case

---

src/components/VaultLocationReport.tsx
src/pages/Welcome.tsx
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/item.test.ts
src/resources/audit/AuditList.tsx
src/resources/destruction/DestructionReport.tsx
src/resources/dispatch/ReportData.tsx
src/resources/items/DestroyItems.tsx
src/resources/items/DispatchItems.tsx
src/resources/items/ItemForm/index.tsx
src/resources/items/ItemList.tsx
src/resources/items/ItemShow.tsx
src/resources/items/ItemsReport.tsx
src/resources/items/index.tsx
src/resources/users/UserMusterList.tsx
src/resources/users/UserShow.tsx
src/types.d.ts
src/utils/generateData.ts

Rename `item.item_number` to `item.itemNumber`

Remove snake case item_number

---

src/components/SourceNestedFilterInput.tsx
src/pages/Welcome.tsx
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/tests/dummy-data.ts
src/resources/batches/BatchReport.tsx
src/resources/batches/BatchShow.tsx
src/resources/destruction/DestructionReport.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemForm/index.tsx
src/resources/items/ItemList.tsx
src/resources/items/ItemsReport.tsx
src/resources/users/UserMusterList.tsx
src/types.d.ts
src/utils/generateData.ts

Rename batchId to batch

---

src/context/NotificationContext.tsx
src/main.tsx
src/resources/items/ItemForm/ItemFormToolbar.tsx

544 item created notification larger

---

src/components/DatagridConfigurableWithShow.tsx

item view button issue fixed

---

src/components/PendingReceiptNotes.tsx
src/components/Recent.tsx
src/pages/Welcome.tsx

include hasteners in receipt notes

---

src/App.tsx
src/resources/items/ItemList.tsx

live items reverse order

---

src/App.tsx
src/resources/items/ItemList.tsx
src/resources/items/ItemListData.tsx
src/resources/items/LocationField.tsx

Different columns for Live Items and All items

---

src/components/HistoryButton.tsx
src/components/ReferenceDataList.tsx
src/resources/batches/BatchShow.tsx
src/resources/destruction/DestructionList.tsx
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/items/ItemShow.tsx
src/resources/platforms/PlatformList.tsx
src/resources/projects/ProjectShow.tsx
src/resources/reference-data/ReferenceDataShow.tsx
src/resources/users/UserShow.tsx
src/resources/vault-locations/VaultLocationList.tsx

add tooltips to buttons

---

src/components/ResourceHistory.tsx
src/resources/audit/AuditList.tsx

refinements to report

---

src/components/Recent.tsx
src/pages/Welcome.tsx
src/resources/batches/BatchForm.tsx
src/resources/items/ItemList.tsx

welcome page improvement

---

src/components/ResourceHistory.tsx
src/resources/audit/AuditList.tsx
src/resources/destruction/DestructionShow.tsx
src/utils/activity-types.ts

audit log on destroy

---

src/resources/items/ItemList.tsx

itemList sticky header fixed

---

src/resources/items/ItemList.tsx

links removed for all columns except loanedTo on itemList

---

src/providers/dataProvider/resource-callbacks/DispatchLifeCycle.ts

changed dispatch prefix to RN

---

src/resources/items/ItemForm/ItemFormToolbar.tsx

added shortcut keys for form submission on item form

---

src/utils/helper.ts

protection string in item create fixed to not include protective marking

---

src/resources/dispatch/DispatchShow.tsx

receipt received in dispatch show

---

src/resources/items/ItemList.tsx

item list item columns bug fixed

---

src/resources/items/ItemList.tsx

destroyed and dispatched filters removed from live items

---

src/resources/items/ItemList.tsx

asset report filtered itemlist

---

src/components/FieldSet.tsx
src/resources/items/ItemHistory.tsx
src/resources/items/ItemShow.tsx

auditlog summary in itemshow

---

src/components/BooleanFilter.tsx

custom filter with nullable fields

---

src/resources/items/ItemForm/ItemFormToolbar.tsx
src/resources/items/ItemForm/index.tsx

increment consect on clone item

---

src/components/DatagridConfigurableWithShow.tsx
src/resources/items/ItemList.tsx
src/resources/items/LoanItemsListBulkActionButtons.tsx

always show action buttons

---

src/components/Printable/index.tsx
src/components/ReportSignature.tsx
src/index.css
src/resources/items/ItemsReport.tsx
src/resources/users/UserMusterList.tsx

muster list report format

---

src/types.d.ts
src/utils/init-data.ts

define bridging tables to RCOStore

---

src/components/ResourceHistory.tsx
src/hooks/useAudit.ts
src/hooks/useVaultLocationAudit.ts
src/providers/authProvider/index.ts
src/providers/dataProvider/dataprovider-utils.ts
src/providers/dataProvider/resource-callbacks/BatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/DestructionLifeCycle.ts
src/providers/dataProvider/resource-callbacks/DispatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/resource-callbacks/LoanCustomMethods.ts
src/providers/dataProvider/resource-callbacks/ReferenceItemLifeCycle.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/items/DestroyItems.tsx
src/resources/items/DestroyRestoreItems.tsx
src/resources/items/DispatchItems.tsx
src/resources/items/ItemList.tsx
src/utils/activity-types.ts
src/utils/audit.ts

569 audit log from legacy

---

src/hooks/useVaultLocationAudit.ts
src/providers/authProvider/index.ts
src/providers/dataProvider/dataprovider-utils.ts
src/providers/dataProvider/resource-callbacks/BatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/DestructionLifeCycle.ts
src/providers/dataProvider/resource-callbacks/DispatchLifeCycle.ts
src/providers/dataProvider/resource-callbacks/ItemLifeCycle.ts
src/providers/dataProvider/resource-callbacks/LoanCustomMethods.ts
src/providers/dataProvider/resource-callbacks/ReferenceItemLifeCycle.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/items/DestroyItems.tsx
src/resources/items/DestroyRestoreItems.tsx
src/resources/items/DispatchItems.tsx
src/resources/items/ItemList.tsx
src/resources/users/UserShow.tsx
src/types.d.ts
src/utils/audit.ts

Capturing more audit data

---

src/providers/authProvider/index.ts

stored the details of the users on login and logout

---

src/App.tsx
src/components/Layout/index.tsx
src/constants.ts
src/pages/Login.tsx
src/providers/authProvider/permissions.ts

permission issues fixed

---

src/resources/items/ItemList.tsx

destroy and dispatch filters changed on all items

---

src/components/VaultLocationReport.tsx
src/providers/dataProvider/tests/dummy-data.ts
src/resources/destruction/DestructionReport.tsx
src/resources/dispatch/ReportData.tsx
src/resources/items/ItemForm/CoreForm.tsx
src/resources/items/ItemForm/ItemFormToolbar.tsx
src/resources/items/ItemShow.tsx
src/resources/items/ItemsReport.tsx
src/resources/users/UserMusterList.tsx
src/types.d.ts
src/utils/generateData.ts

Fixes #622 
(note: SQLite modified in 471 SQlite branch)

622 Rename `Pages` to `Sheets` in the front-end

---

src/components/ProtectionBlockInputs.tsx
src/components/ProtectionRefInput.tsx

fixed fresh item containing lots of codes, caves 

---

src/providers/dataProvider/index.ts

fixes #643 
Reference: [better-sqlite3 docs](https://github.com/WiseLibs/better-sqlite3/blob/HEAD/docs/api.md#runbindparameters---object)

destruction page crashing fixed after printing

---

src/resources/batches/index.tsx

redirected to batch show page after batch create

---

.env
package.json
src/providers/dataProvider/index.ts

Let `Soul` serve on it's default port. Modify front-end to reflect that.

soul port changed from 4000 to 8000

---

package.json
yarn.lock

Tested `date` filters and `date range` filters and they are working fine.
Fixes #642

updated soul-cli with fixed date__gte and date__lte issues

---

src/resources/destruction/DestructionForm.tsx

save button enabled by default

---

src/components/DatePicker.tsx

fixed date bug on new batch

---

src/resources/destruction/DestructionShow.tsx

items can be removed from destruction

---

README.md
db/.project
index.html
src/components/Layout/index.tsx
src/components/VaultLocationReport.tsx
src/pages/Login.tsx
src/resources/items/ItemsReport.tsx
src/resources/users/UserMusterList.tsx

rebranded to VAL

---

src/resources/items/ItemList.tsx
src/resources/items/ItemShow.tsx

Allow search and view of Legacy Media Type

---

src/components/Recent.tsx
src/resources/dispatch/DispatchList.tsx

Hotfix dispatch data

---

src/components/PendingReceiptNotes.tsx
src/resources/destruction/DestructionList.tsx
src/resources/dispatch/DispatchList.tsx
src/resources/dispatch/DispatchShow.tsx

minor bug fix and welcome page receipt notes filter fixed

---

src/resources/dispatch/DispatchForm.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/dispatch/index.tsx

non-sent dispatches can be edited

---

src/resources/batches/BatchForm.tsx
src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchForm.tsx

vault not showing on dispatch fixed

---

src/components/ReferenceDataList.tsx
src/resources/platforms/PlatformList.tsx
src/resources/vault-locations/VaultLocationList.tsx

active filter added on reference data list

---

src/components/ProtectionBlockInputs.tsx

fixes #742 
Couldn't edit in `SQLite` backend because of foreign key constraints.

id shown for handling instruction on item show

---

src/resources/platforms/PlatformList.tsx
src/resources/projects/ProjectList.tsx

filters added on project listing

---

src/pages/Welcome.tsx

resource fixed on welcome page recent loan

---

src/resources/items/ItemList.tsx
src/utils/init-data.ts

project column label changed on live and all items

---

src/resources/items/index.tsx

item show link fixed on item form show button

---

package.json
src/providers/dataProvider/index.ts
src/utils/helper.ts

`NODE_ENV` added for switching api url for `production` and `development`

api url bug fixed for development

---

src/resources/batches/BatchList.tsx
src/resources/items/ItemList.tsx

project column fixed on item list and batch list pages

---

src/components/ReferenceDataList.tsx
src/pages/ReferenceData.tsx
src/resources/addresses/AddressList.tsx
src/resources/destruction/DestructionList.tsx
src/resources/dispatch/DispatchList.tsx
src/resources/platforms/PlatformList.tsx
src/resources/users/UserList.tsx
src/resources/vault-locations/VaultLocationList.tsx

added search bar to different pages

---

src/resources/dispatch/DispatchForm.tsx

link to go to address listing page added on dispatch create page

---

src/resources/vault-locations/VaultLocationList.tsx

create button added for vault locations

---

src/resources/users/UserForm.tsx
src/resources/users/index.tsx

removed password field for user

---

src/resources/items/ItemForm/ChangeLocation.tsx

item location change bug fixed

---

src/resources/users/UserForm.tsx

user role made optional in user form

---

src/providers/dataProvider/dataprovider-utils.ts

password removed from audit logs

---

_extensions/api.js

Trial alternate method to get IP Address

---

src/components/ProtectionRefInput.tsx

save/clone not capturing itemCode, itemCave and itemHandle fixed

---

src/providers/dataProvider/dataprovider-utils.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/user.test.ts

unnecessary password assigned event in audit log fixed

---

src/resources/audit/AuditList.tsx

filter by user fixed on audit list

---

src/pages/Login.tsx
src/providers/authProvider/index.ts
src/resources/users/UserList.tsx
src/resources/users/UserShow.tsx
src/utils/helper.ts

extra features for departed users

---

src/App.tsx
src/pages/Login.tsx

Reveal Password button

---

src/components/EditToolBar.tsx
src/resources/reference-data/ReferenceDataForm.tsx

edit toolbar not considering form validation fixed

---

src/resources/items/ItemList.tsx
src/resources/items/ItemShow.tsx

858 pending item location

---

src/hooks/useAudit.ts
src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/providers/dataProvider/tests/user.test.ts
src/resources/users/UserShow.tsx

fixes #852 
_Note:_ Need to know if the activity detail is ok or should be changed? Also need to discuss `User Edit` activity type in `beforeUpdate`

user audits refactored

---

src/resources/users/UserMusterList.tsx

reinstated project and platform on user muster list

---

src/providers/dataProvider/dataprovider-utils.ts

dispatch number generation fixed

---

src/components/SourceField.tsx
src/resources/audit/AuditList.tsx
src/resources/batches/BatchList.tsx
src/resources/dispatch/DispatchShow.tsx
src/resources/items/ItemHistory.tsx
src/resources/items/ItemList.tsx

844 remove items from completed dispatch

---

src/components/VaultLocationReport.tsx

count missing from muster list fixed

---

src/components/VaultLocationReport.tsx

records missing on page-break fixed

---

src/resources/items/ItemForm/index.tsx

Error messages on item form improved

---

src/resources/batches/BatchList.tsx
src/resources/items/ItemList.tsx

department filter added on batch list and item list

---

src/components/TopToolbarField.tsx
src/components/VaultLocationReport.tsx
src/pages/Welcome.tsx
src/resources/audit/AuditList.tsx
src/resources/batches/BatchList.tsx
src/resources/batches/BatchShow.tsx
src/resources/items/ItemList.tsx
src/resources/items/ItemShow.tsx
src/resources/users/UserMusterList.tsx
src/resources/users/UserShow.tsx

prefix added for item number and batch number

---

src/resources/users/UserShow.tsx

user show fixed with lots of loaned items

---

src/components/Layout/index.tsx

removed buttons from user menu

---

src/resources/users/UserShow.tsx

console errors fixed

---

src/providers/dataProvider/resource-callbacks/UserLifeCycle.ts
src/providers/dataProvider/tests/dummy-data.ts
src/providers/dataProvider/tests/user.test.ts
src/resources/users/UserShow.tsx

departed date for new users set to 10 years in future

---

src/App.tsx
src/hooks/tests/protected-route.test.tsx
src/hooks/useCanAccess.ts
src/providers/authProvider/permissions.ts
src/providers/dataProvider/index.ts
src/resources/users/UserShow.tsx
src/types.d.ts

no user can delete any resource

---

_extensions/api.js

login api not working on production soul fixed

---

src/providers/authProvider/permissions.ts

empty all item page bug fixed

---

_devExtensions/login-controller.js
src/pages/Login.tsx
src/pages/Welcome.tsx
src/resources/users/UserForm.tsx
src/resources/users/UserList.tsx
src/resources/users/UserShow.tsx

renamed staffNumber to Username

---

src/index.css
src/pages/Login.tsx

test users removed and reveal password button removed from login page

---

_devExtensions/login-controller.js
src/providers/authProvider/index.ts

A user is having trouble logging in, due to number of lockouts exceeded.
Introduce diagnostics to help understand this.

Introduce diagnostics

---

package.json
yarn.lock

changed better sqlite version

---

src/constants.ts
src/resources/addresses/index.tsx
src/resources/batches/index.tsx
src/resources/destruction/index.tsx
src/resources/dispatch/index.tsx
src/resources/items/index.tsx
src/resources/projects/index.tsx
src/resources/reference-data/index.tsx
src/resources/users/UserShow.tsx
src/resources/users/index.tsx
src/resources/vault-locations/index.tsx

Adopt optimistic record locking

---

_devExtensions/api.js
_devExtensions/changePassword-controller.js
_extensions/api.js
src/App.tsx
src/ChangePassword.tsx
src/components/Layout/index.tsx
src/constants.ts
src/providers/authProvider/index.ts
src/utils/activity-types.ts
src/utils/helper.ts

change password functionalities implemented

---

src/resources/audit/AuditList.tsx
src/resources/users/index.tsx

Audit log on edit to user table resolved

---

src/utils/password-validation.schema.ts

clarify special character issue resolved

---

src/resources/audit/AuditList.tsx

item remove from filter in audit log

---

src/components/Layout/Footer.tsx

added build date into the footer

---

src/resources/addresses/AddressList.tsx
src/types.d.ts
src/utils/init-data.ts

remarks were not showing into the address list issue resolved

---

src/resources/reference-data/ReferenceDataForm.tsx
src/resources/reference-data/ReferenceDataShow.tsx

media type need edit issue resolved

---

src/resources/users/UserForm.tsx

Departure date edit able issue resolved

---

src/hooks/useCustomId.ts

966 - unique value for new mediaType id

---

src/hooks/useCustomId.ts
src/resources/destruction/DestructionForm.tsx

save not working for destuction edit issue resolved

---

src/resources/users/UserShow.tsx
src/resources/users/index.tsx

user show history doesn't filter results issue resolved

---

src/components/DateFilter.tsx

auditlist filter for date misses for today issue resolved

---

src/providers/authProvider/permissions.ts
src/resources/users/UserShow.tsx

rco-user not able to edit any user profile

---

src/App.tsx

980 password reset should clear the min password age issue resolved

---

src/pages/ReferenceData.tsx
src/providers/dataProvider/index.ts
src/resources/reference-data/ReferenceDataForm.tsx
src/resources/reference-data/index.tsx

field for id-Dept, warning massage implementd

---

src/resources/users/UserForm.tsx
src/resources/users/index.tsx

cannot create new user issue resolved

---

src/resources/platforms/index.tsx

platform edits not saved issue resolved

---

src/components/VaultLocationReport.tsx

invalid count on muster list issue resolved

---

src/resources/dispatch/ReportData.tsx
src/resources/items/DispatchItems.tsx

recipient name not shown in receipt note issue resolved

---

src/resources/items/ItemShow.tsx

display time for start and end for itemshow issue resolved

---

src/App.tsx

fixes old code

---

src/resources/addresses/AddressForm.tsx
src/resources/addresses/index.tsx

delete removed from address edit.

---

src/resources/batches/BatchList.tsx
src/resources/items/ItemList.tsx

in batch list and item list the porject is not click able now.

---

src/resources/vault-locations/VaultLocationList.tsx

sorting vault locations issue resolved

---

src/resources/addresses/AddressList.tsx
src/resources/audit/AuditList.tsx
src/resources/destruction/DestructionList.tsx
src/resources/dispatch/DispatchList.tsx
src/resources/items/ItemHistory.tsx

export button removed

---

src/resources/batches/BatchList.tsx

need to sort batchlist by reference issue resolved

---

src/providers/dataProvider/index.ts
src/resources/addresses/AddressForm.tsx
src/resources/addresses/index.tsx

fixes #1006 
Fixes #1003 
Fixes #1005

single quote issue resolved

---

src/components/Layout/index.tsx

button to reset displayed columns issue resolved

---

src/resources/batches/BatchList.tsx

batchlist cannot filter for active platform issue resolved

---

.env
package.json
src/components/Layout/index.tsx
src/themes/rco-theme.ts
vite.config.ts

offer cosmetic clues of working on test server issue resolved

---

src/pages/Login.tsx

change background color of login page

---

src/resources/addresses/AddressForm.tsx
src/resources/destruction/DestructionForm.tsx
src/resources/dispatch/DispatchForm.tsx
src/resources/platforms/index.tsx
src/resources/reference-data/ReferenceDataForm.tsx
src/resources/reference-data/ReferenceDataShow.tsx
src/resources/reference-data/index.tsx
src/resources/reference-data/utils.ts
src/resources/vault-locations/VaultLocationForm.tsx
src/resources/vault-locations/index.tsx

add title on create and edit form

---

src/components/VaultLocationReport.tsx

Reduce network calls to populate muster list

---

src/components/ReferenceDataList.tsx
src/resources/addresses/AddressList.tsx
src/resources/platforms/PlatformList.tsx

List pages missing title issue resolved

---

src/components/VaultLocationReport.tsx

Increase number of rows fetched for summary table

---

src/resources/reference-data/ReferenceDataForm.tsx

Id field added in create form

---

src/resources/addresses/AddressList.tsx

delete button removed from address list

---

src/resources/destruction/DestructionForm.tsx

remarks in destruction is now optional

---

src/resources/projects/ProjectForm.tsx

now active button editable in project form

---

src/resources/destruction/DestructionForm.tsx

make remarks optional on destruction create form.

---

src/components/DatagridConfigurableWithShow.tsx

ctrl-click handler applied on viewItem icon

---

src/components/StyledTopToolbar.tsx

filter on batch list displayed in vertical form issue fixed

---

src/providers/authProvider/index.ts

Logging in as a user with no role gives blank page issue resolved

---

src/resources/reference-data/ReferenceDataShow.tsx

Remove duplicate edit button

---

src/App.tsx

Provide context-sensitive title to reset password dialog.

---

db/Scripts/business.sql
src/components/SourceInput.tsx
src/pages/Login.tsx
src/resources/items/LoanItemsListBulkActionButtons.tsx
src/utils/password-validation.schema.ts

Adopt new field title, drop staffNumber

---

src/hooks/useVaultLocationAudit.ts

1073 unable to change vault location from batchshow page

---

src/resources/items/ItemList.tsx

1058 filter of destruction on item list not showing complete results

---

src/utils/helper.ts

refresh rendering issue resolved

---

package.json
yarn.lock

Custom PR to test Soul fix: https://github.com/thevahidal/soul/pull/183

Provide dependency on specific commit

---

src/utils/helper.ts

Fixes #1090 
Current password issue resolved.

fixed current password issue

---

_devExtensions/api.js
src/ChangePassword.tsx
src/resources/users/UserShow.tsx
src/utils/helper.ts

1092 - single logic for update and change password first commit

---

src/ChangePassword.tsx
src/resources/users/UserShow.tsx

1099 1097 edit pwd guidance cancel

---

_devExtensions/api.js
_devExtensions/updateBefore-controller.js
src/utils/helper.ts

1100_update_before_diagnostics

---

_extensions/api.js

Fixes #1100 
1. Exported the `update-before` custom endpoint from the `_extension` directory

Exported the update-before custom endpoint from the _extension dir

---

_devExtensions/updateBefore-controller.js
src/utils/helper.ts

Fixes #1100 
Remove debug lines generated while resolving issue #1100

Remove debug lines

---

package.json
yarn.lock

Restore cross-env dependency

---

package.json
src/resources/users/UserForm.tsx

Add description note on user create and edit page.

---

src/providers/authProvider/permissions.ts

removed reference-data for default user.

---

src/resources/destruction/DestructionShow.tsx
src/resources/dispatch/DispatchList.tsx
src/resources/dispatch/DispatchShow.tsx

no reciept notes for default_user

---

src/components/DatagridConfigurableWithShow.tsx

fix: add link icon for items and items details show on new page.
